site_name: DERIVA Documentation
site_description: Documentation for DERIVA software.
site_url: https://informatics-isi-edu.github.io/deriva-docs/
theme: readthedocs
extra_css: 
  - css/extra.css #this is a standard css sheet


pages:
- Welcome to the documentation: index.md
- Using DERIVA:
    - Installing: install.md
- Key Concepts:
    - DERIVA Key Concepts: concepts.md
#    - Supporting Pages such as: Resource Naming: model-resource-naming.md
- Developing with DERIVA:
    - Guidelines for Development: development.md


markdown_extensions:
    - toc:
        permalink: True
    - admonition:

copyright: Copyright &copy; 2018 <a href="http://github.com/informatics-isi-edu/ermrest">ERMrest Project</a>.